version: '3.8'

services:
  data_processor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: data_processor
    container_name: data_processor
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    container_name: air_quality_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: air_quality
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: