version: '3.8'

services:
  data_processor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: data_processor
    container_name: data_processor
    volumes:
      - ./data:/app/data